name: default

service: 
- name: web
  resources:
  - ref: redis/web-redis
  - ref: cloudsql/web-sql
  
- name: preston
  image: us-docker.pkg.dev/cloudrun/container/hello
  resources:
  - ref: redis/web-redis

 
router:
- name: web-router
  domain: livedemo.jmahood.com
  default-route:
    ref: service/web

redis:
- name: web-redis
  instance: 
    memory-size-gb: 4

cloudsql:
- name: web-sql
  version: POSTGRES_11
  settings:
    tier: db-f1-micro
  
  
