name: default

service: 
- name: web
  resources:
  - ref: redis/web-redis
  
- name: service2
  image: us-docker.pkg.dev/cloudrun/container/hello
  resources:
  - ref: redis/web-redis
 
router:
- name: web-router
  domain: livedemo.jmahood.com
  default-route:
    ref: service/web

redis:
- name: web-redis
  instance: 
    memory-size-gb: 4
