name: default

service: 
- name: web
  resources:
  - ref: redis/web-redis
 
router:
- name: web-router
  domain: livedemo.jmahood.com
  default-route:
    ref: service/web

redis:
- name: web-redis
  instance: 
    memory-size-gb: 4
  
scheduler:
- name: job
  config:
    schedule: "* * * * *"
    http-method: POST
    body: "doesn't matter"
  resource:
    ref: service/web
    path: /
  
